routes:

collections:

  /lesson/:
    permalink: /lesson/{slug}/
    template: course
    filter: "tag:hash-lesson"

  /courses/:
    permalink: /course/{slug}/
    template: courses
    filter: "tag:hash-course"

  /blog/:
    permalink: /blog/{slug}/
    template: blog
    filter: "tag:hash-blog"
    
  /news/:
    permalink: /news/{slug}/
    template: news
    filter: "tag:hash-news"

  /:
    permalink: /course/{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
