name: Run yarn run dev on main branch

on:
  push:
    branches:
      - main

jobs:
  dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2 

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.12.1
        
      - name: Install dependencies
        run: yarn install  
        
      - name: Start dev server
        run: |
          nohup yarn run dev &
       
      - name: Wait for Ghost server to start
        run: |
          while ! curl --output /dev/null --silent --fail http://localhost:2368; do
            sleep 1
          done
      
      - name: Install gssg
        run: npm install -g ghost-static-site-generator
        
      - name: Reset
        run: git reset --hard origin/test
      
      - name: List files in current directory
        run: ls
        
      - name: Generate static site
        run: gssg
        
      - name: List files in current directory
        run: ls ./static
        
      - name: Set up Git
        run: |
          git config --global user.name "LongfeiH"
          git config --global user.email "2069860997@qq.com"

      - name: Copy HTTrack files to gh-pages branch
        run: |
          git add ./static/*
          git commit -m "Update branch"
          git push origin test --force
