name: Run yarn run dev on main branch

on:
  push:
    branches:
      - main

jobs:
  dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          
      - name: Switch to main branch
        run: git checkout main    

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.12.1
        
      - name: Install dependencies
        run: yarn install  

      - name: Install HTTrack
        run: sudo apt-get install httrack
        
      - name: Yarn run dev
        run: yarn run dev &

      - name: Wait for Ghost server to start
        run: |
          while ! curl --output /dev/null --silent --fail http://localhost:2368; do
            sleep 2
          done  

      - name: Run HTTrack
        run: httrack --mirror localhost:2368 -v
        
      - name: Set up Git
        run: |
          git config --global user.name "LongfeiH"
          git config --global user.email "2069860997@qq.com"

      - name: Copy HTTrack files to gh-pages branch
        run: |
          git add .
          git commit -m "Update gh-pages branch"
          git push origin gh-pages  
